module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      height: {
        em1: "1vh",
        em2: "2vh",
        em3: "3vh",
        em4: "4vh",
        em5: "5vh",
        em6: "6vh",
        em7: "7vh",
        em8: "8vh",
        em9: "9vh",
        em10: "10vh",
      },
      weight: {
        em1: "1vw",
        em2: "2vw",
        em3: "3vw",
        em4: "4vw",
        em5: "5vw",
        em6: "6vw",
        em7: "7vw",
        em8: "8vw",
        em9: "9vw",
        em10: "10vw",
      },
      margin: {
        em1: "1vw",
        em2: "2vw",
        em3: "3vw",
        em4: "4vw",
        em5: "5vw",
        em6: "6vw",
        em7: "7vw",
        em8: "8vw",
        em9: "9vw",
        em10: "10vw",
      },
      padding: {
        em1: "1vw",
        em2: "2vw",
        em3: "3vw",
        em4: "4vw",
        em5: "5vw",
        em6: "6vw",
        em7: "7vw",
        em8: "8vw",
        em9: "9vw",
        em10: "10vw",
      },
      borderWidth: {
        em1: "1vw",
        em2: "2vw",
        em3: "3vw",
        em4: "4vw",
        em5: "5vw",
        em6: "6vw",
        em7: "7vw",
        em8: "8vw",
        em9: "9vw",
        em10: "10vw",
      },
      fontSize: {
        em1: "1vw",
        em1_5: "1.5vw",
        em2: "2vw",
        em2_5: "2.5vw",
        em3: "3vw",
        em3_5: "3.5vw",
        em4: "4vw",
        em4_5: "4.5vw",
        em5: "5vw",
        em5_5: "5.5vw",
        em6: "6vw",
        em7: "7vw",
        em8: "8vw",
        em9: "9vw",
        em10: "10vw",
        em15: "15vw",
        em20: "20vw",
        em25: "25vw",
        em30: "30vw",
        em40: "40vw",
      },
      backgroundImage: {
        landing: "url('/src/img/bg.jpg')",
        loader: "url('/src/img/Loader.gif')",
        load: "url('/src/img/Load.gif')",
      },
    },
  },
  plugins: [],
};
